

on:
    push:
        branches:
            - main
    pull_request:
         branches:
            - main
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
          
            - name: Clone and Check repistory
              uses: actions/checkout@v4
            - name: Set-up Bun
              uses: oven-sh/setup-bun@v2
              with:
                bun-version: 1.2.21
            - name: Install Dependencies
              run: bun install
            - name: Build
              run: bun run build

            
