name: websocket pipeline
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    deploy-websocket-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repistory
              uses: actions/checkout@v4
            - name: Docker login
              uses: docker/login-action@v3
              with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./Docker/Dockerfile.websocket
                push: true
                tags: ginnysingh789/websocket:${{github.sha}}